import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import "@sweetalert2/theme-bootstrap-4";
import NoShow from "@/components/NoShow/NoShow";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "You Drive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NoShow>
          <Navbar></Navbar>
        </NoShow>

        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
