server {
        listen 443 ssl;
        server_name youdrive-grafana.duckdns.org;

        ssl_certificate /etc/letsencrypt/live/youdrive-grafana.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/youdrive-grafana.duckdns.org/privkey.pem;

        deny 142.93.110.238;
        deny 165.22.94.45;
        deny 52.76.71.100;
        deny 61.0.219.79;
        deny 135.125.246.189;
        deny 172.212.61.129;
        deny 185.254.196.173;
        deny 46.174.191.30;
        deny 185.254.196.173;
        deny 89.187.164.134;
        deny 43.129.169.161;
        deny 45.79.172.21;
        deny 135.125.246.110;
        deny 78.153.140.179;
        deny 45.79.181.251;
        deny 185.254.196.186;
        deny 84.54.51.37;
        deny 186.12.229.75;

        location / {
            proxy_pass http://localhost:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
}