export const mockPosts = [
  {
    id: 1,
    title: "ALQUILO DE VEHICULOS",
    description: "Kia Sorento en excelente estado para alquilar",
    user_id: {
      id: 1,
      name: "Santi",
      lastname: "Perez",
      email: "santi.perez@example.com",
    },
    cars_id: {
      id: 1,
      brand: "Kia",
      model: "Sorento",
      year: 2020,
      mileage: "15,000 km",
      color: "white",
      price: 1200000,
      type: "SUV",
      availability: true,
      image_url:
        "https://distrikia.com.co/wp-content/uploads/2024/01/Distrikia-kia-sorento-miniatura-3.webp",
    },
  },
  {
    id: 2,
    title: "ALQUILO DE VEHICULOS",
    description: "Chevrolet Camaro listo para alquilar",
    user_id: {
      id: 2,
      name: "Maria",
      lastname: "Lopez",
      email: "maria.lopez@example.com",
    },
    cars_id: {
      id: 2,
      brand: "Chevrolet",
      model: "Camaro",
      year: 2019,
      mileage: "20,000 km",
      color: "red",
      price: 1500000,
      type: "Deportivo",
      availability: false,
      image_url:
        "https://www.autosrodando.com/wp-content/uploads/2023/06/chevrolet-camaro-2024-zl1-collector-s-edition-1280x720.jpg.webp",
    },
  },
  {
    id: 3,
    title: "ALQUILO DE VEHICULOS",
    description: "Mazda CX-5 disponible para alquilar",
    user_id: {
      id: 3,
      name: "Pedro",
      lastname: "Gonzalez",
      email: "pedro.gonzalez@example.com",
    },
    cars_id: {
      id: 3,
      brand: "Mazda",
      model: "CX-5",
      year: 2021,
      mileage: "10,000 km",
      color: "blue",
      price: 1300000,
      type: "SUV",
      availability: true,
      image_url:
        "https://mazda.casatoro.com/assets/img/Mazda_CX_5_lateral_11zon_e76e5bf19a.74438a4c.webp",
    },
  },
  {
    id: 4,
    title: "ALQUILO DE VEHICULOS",
    description: "Ford F-150 para alquiler",
    user_id: {
      id: 4,
      name: "Lucia",
      lastname: "Martinez",
      email: "lucia.martinez@example.com",
    },
    cars_id: {
      id: 4,
      brand: "Ford",
      model: "F-150",
      year: 2018,
      mileage: "30,000 km",
      color: "black",
      price: 1600000,
      type: "Camioneta",
      availability: false,
      image_url:
        "https://acnews.blob.core.windows.net/imgnews/medium/NAZ_918487fd7b3e4c6b8f3eefb369a0853b.webp",
    },
  },
  {
    id: 5,
    title: "ALQUILO DE VEHICULOS",
    description: "Kia Rio en perfecto estado para alquilar",
    user_id: {
      id: 5,
      name: "Jorge",
      lastname: "Ramirez",
      email: "jorge.ramirez@example.com",
    },
    cars_id: {
      id: 5,
      brand: "Kia",
      model: "Rio",
      year: 2022,
      mileage: "5,000 km",
      color: "silver",
      price: 1400000,
      type: "Sedan",
      availability: true,
      image_url:
        "https://www.diariomotor.com/imagenes/2022/01/kia-rio-vista-lateral-794707-720x385.webp",
    },
  },
];
